### ISSUE TITLE
lib64/android.hardware.boot@1.0.so needed

### ISSUE THREAD

**Issue by JengaMasterG** [mauronofrio/android_device_blackshark_shark#1]
`ninja: error: '/home/giovanni/Desktop/TWRP/development/out/system/lib64/android.hardware.boot@1.0.so', needed by '/home/giovanni/Desktop/TWRP/development/out/target/product/shark/obj_arm/SHARED_LIBRARIES/libbmlutils_intermediates/teamwin', missing and no known rule to make it
14:16:46 ninja failed with: exit status 1
`

**Comment by mauronofrio** [comment]
are you buildinf the twrp under omni-8.1 or minimal twrp manifest 8.1?

**Comment by JengaMasterG** [comment]
I'm currently using minimal and have put ALLOW_MISSING_DEPENDENCIES :=true in BoardConfig.mk

**Comment by mauronofrio** [comment]
are you using minimal 8.1?

**Comment by JengaMasterG** [comment]
I may have accidentally downloaded 9.0. Would that cause this issue?

**Comment by mauronofrio** [comment]
Yes

**Comment by JengaMasterG** [comment]
Ok thanks. Is there a chance to make this device tree compatible with 9.0?

**Comment by mauronofrio** [comment]
This twrp is already ready to work on pie, you don't need to update it

**Comment by mauronofrio** [comment]
Sorry i forgot to update a commit, i have it on my pc...

**Comment by JengaMasterG** [comment]
Thanks!! I'll close the issue then 👍

**Comment by duyleekun** [comment]
> This twrp is already ready to work on pie, you don't need to update it

Can you put the pie twrp in the releases?
